package insurance;
// Generated Jul 18, 2015 12:33:04 AM by Hibernate Tools 3.6.0



/**
 * CustPolicyDetails generated by hbm2java
 */
public class CustPolicyDetails  implements java.io.Serializable {


     private Integer cpdid;
     private Policies policies;
     private Customer customer;

    public CustPolicyDetails() {
    }

    public CustPolicyDetails(Policies policies, Customer customer) {
       this.policies = policies;
       this.customer = customer;
    }
   
    public Integer getCpdid() {
        return this.cpdid;
    }
    
    public void setCpdid(Integer cpdid) {
        this.cpdid = cpdid;
    }
    public Policies getPolicies() {
        return this.policies;
    }
    
    public void setPolicies(Policies policies) {
        this.policies = policies;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


