package insurance;
// Generated Jul 18, 2015 12:33:04 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer cid;
     private String cname;
     private String address;
     private String mob;
     private Date bdate;
     private String gender;
     private int pincode;
     private String status;
     private byte[] photo;
     private byte[] idproof;
     private String password;
     private String city;
     private String state;
     private Set policyRegistrations = new HashSet(0);
     private Set custPolicyDetailses = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String cname, String address, String mob, Date bdate, String gender, int pincode, String password, String city, String state) {
        this.cname = cname;
        this.address = address;
        this.mob = mob;
        this.bdate = bdate;
        this.gender = gender;
        this.pincode = pincode;
        this.password = password;
        this.city = city;
        this.state = state;
    }
    public Customer(String cname, String address, String mob, Date bdate, String gender, int pincode, String status, byte[] photo, byte[] idproof, String password, String city, String state, Set policyRegistrations, Set custPolicyDetailses) {
       this.cname = cname;
       this.address = address;
       this.mob = mob;
       this.bdate = bdate;
       this.gender = gender;
       this.pincode = pincode;
       this.status = status;
       this.photo = photo;
       this.idproof = idproof;
       this.password = password;
       this.city = city;
       this.state = state;
       this.policyRegistrations = policyRegistrations;
       this.custPolicyDetailses = custPolicyDetailses;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMob() {
        return this.mob;
    }
    
    public void setMob(String mob) {
        this.mob = mob;
    }
    public Date getBdate() {
        return this.bdate;
    }
    
    public void setBdate(Date bdate) {
        this.bdate = bdate;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public byte[] getIdproof() {
        return this.idproof;
    }
    
    public void setIdproof(byte[] idproof) {
        this.idproof = idproof;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getPolicyRegistrations() {
        return this.policyRegistrations;
    }
    
    public void setPolicyRegistrations(Set policyRegistrations) {
        this.policyRegistrations = policyRegistrations;
    }
    public Set getCustPolicyDetailses() {
        return this.custPolicyDetailses;
    }
    
    public void setCustPolicyDetailses(Set custPolicyDetailses) {
        this.custPolicyDetailses = custPolicyDetailses;
    }




}


