package insurance;
// Generated Jul 18, 2015 12:33:04 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private Integer mid;
     private int mgrssn;
     private String mname;
     private String maddress;
     private String location;
     private String mgender;
     private Date mbdate;
     private int mage;
     private String mpassword;
     private byte[] mphoto;

    public Manager() {
    }

	
    public Manager(int mgrssn, String mname, String maddress, String location, String mgender, Date mbdate, int mage, String mpassword) {
        this.mgrssn = mgrssn;
        this.mname = mname;
        this.maddress = maddress;
        this.location = location;
        this.mgender = mgender;
        this.mbdate = mbdate;
        this.mage = mage;
        this.mpassword = mpassword;
    }
    public Manager(int mgrssn, String mname, String maddress, String location, String mgender, Date mbdate, int mage, String mpassword, byte[] mphoto) {
       this.mgrssn = mgrssn;
       this.mname = mname;
       this.maddress = maddress;
       this.location = location;
       this.mgender = mgender;
       this.mbdate = mbdate;
       this.mage = mage;
       this.mpassword = mpassword;
       this.mphoto = mphoto;
    }
   
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }
    public int getMgrssn() {
        return this.mgrssn;
    }
    
    public void setMgrssn(int mgrssn) {
        this.mgrssn = mgrssn;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getMaddress() {
        return this.maddress;
    }
    
    public void setMaddress(String maddress) {
        this.maddress = maddress;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getMgender() {
        return this.mgender;
    }
    
    public void setMgender(String mgender) {
        this.mgender = mgender;
    }
    public Date getMbdate() {
        return this.mbdate;
    }
    
    public void setMbdate(Date mbdate) {
        this.mbdate = mbdate;
    }
    public int getMage() {
        return this.mage;
    }
    
    public void setMage(int mage) {
        this.mage = mage;
    }
    public String getMpassword() {
        return this.mpassword;
    }
    
    public void setMpassword(String mpassword) {
        this.mpassword = mpassword;
    }
    public byte[] getMphoto() {
        return this.mphoto;
    }
    
    public void setMphoto(byte[] mphoto) {
        this.mphoto = mphoto;
    }




}


