package insurance;
// Generated Jul 18, 2015 12:33:04 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PolicyRegistration generated by hbm2java
 */
public class PolicyRegistration  implements java.io.Serializable {


     private Integer policyNo;
     private Agents agents;
     private Customer customer;
     private double planamount;
     private double installemnt;
     private Double paidamount;
     private double sumassured;
     private Double balance;
     private int term;
     private Date regdate;
     private String nominee;
     private String status;
     private String installmentType;

    public PolicyRegistration() {
    }

	
    public PolicyRegistration(double planamount, double installemnt, double sumassured, int term, Date regdate, String installmentType) {
        this.planamount = planamount;
        this.installemnt = installemnt;
        this.sumassured = sumassured;
        this.term = term;
        this.regdate = regdate;
        this.installmentType = installmentType;
    }
    public PolicyRegistration(Agents agents, Customer customer, double planamount, double installemnt, Double paidamount, double sumassured, Double balance, int term, Date regdate, String nominee, String status, String installmentType) {
       this.agents = agents;
       this.customer = customer;
       this.planamount = planamount;
       this.installemnt = installemnt;
       this.paidamount = paidamount;
       this.sumassured = sumassured;
       this.balance = balance;
       this.term = term;
       this.regdate = regdate;
       this.nominee = nominee;
       this.status = status;
       this.installmentType = installmentType;
    }
   
    public Integer getPolicyNo() {
        return this.policyNo;
    }
    
    public void setPolicyNo(Integer policyNo) {
        this.policyNo = policyNo;
    }
    public Agents getAgents() {
        return this.agents;
    }
    
    public void setAgents(Agents agents) {
        this.agents = agents;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public double getPlanamount() {
        return this.planamount;
    }
    
    public void setPlanamount(double planamount) {
        this.planamount = planamount;
    }
    public double getInstallemnt() {
        return this.installemnt;
    }
    
    public void setInstallemnt(double installemnt) {
        this.installemnt = installemnt;
    }
    public Double getPaidamount() {
        return this.paidamount;
    }
    
    public void setPaidamount(Double paidamount) {
        this.paidamount = paidamount;
    }
    public double getSumassured() {
        return this.sumassured;
    }
    
    public void setSumassured(double sumassured) {
        this.sumassured = sumassured;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public int getTerm() {
        return this.term;
    }
    
    public void setTerm(int term) {
        this.term = term;
    }
    public Date getRegdate() {
        return this.regdate;
    }
    
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
    public String getNominee() {
        return this.nominee;
    }
    
    public void setNominee(String nominee) {
        this.nominee = nominee;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getInstallmentType() {
        return this.installmentType;
    }
    
    public void setInstallmentType(String installmentType) {
        this.installmentType = installmentType;
    }




}


