package insurance;
// Generated Jul 18, 2015 12:33:04 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Policies generated by hbm2java
 */
public class Policies  implements java.io.Serializable {


     private Integer pid;
     private String pname;
     private Integer term;
     private Double sumAssured;
     private float rate;
     private String installment;
     private Float commission;
     private Set custPolicyDetailses = new HashSet(0);

    public Policies() {
    }

	
    public Policies(String pname, float rate) {
        this.pname = pname;
        this.rate = rate;
    }
    public Policies(String pname, Integer term, Double sumAssured, float rate, String installment, Float commission, Set custPolicyDetailses) {
       this.pname = pname;
       this.term = term;
       this.sumAssured = sumAssured;
       this.rate = rate;
       this.installment = installment;
       this.commission = commission;
       this.custPolicyDetailses = custPolicyDetailses;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(Integer term) {
        this.term = term;
    }
    public Double getSumAssured() {
        return this.sumAssured;
    }
    
    public void setSumAssured(Double sumAssured) {
        this.sumAssured = sumAssured;
    }
    public float getRate() {
        return this.rate;
    }
    
    public void setRate(float rate) {
        this.rate = rate;
    }
    public String getInstallment() {
        return this.installment;
    }
    
    public void setInstallment(String installment) {
        this.installment = installment;
    }
    public Float getCommission() {
        return this.commission;
    }
    
    public void setCommission(Float commission) {
        this.commission = commission;
    }
    public Set getCustPolicyDetailses() {
        return this.custPolicyDetailses;
    }
    
    public void setCustPolicyDetailses(Set custPolicyDetailses) {
        this.custPolicyDetailses = custPolicyDetailses;
    }




}


